'use client';

import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useFieldArray, useFormContext } from 'react-hook-form';

import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Radio from '@mui/material/Radio';
import Typography from '@mui/material/Typography';
import CardContent from '@mui/material/CardContent';
import IconButton from '@mui/material/IconButton';
import RadioGroup from '@mui/material/RadioGroup';
import FormControl from '@mui/material/FormControl';

import { Iconify } from 'src/components/iconify';
import { Field } from 'src/components/hook-form';
import { Label } from 'src/components/label';

// ----------------------------------------------------------------------

/**
 * PhoneLabel enum options
 */
const PHONE_LABEL_OPTIONS = [
  { value: 1, label: 'Main' },
  { value: 2, label: 'Delivery' },
  { value: 3, label: 'Reservations' },
];

// ----------------------------------------------------------------------

/**
 * Phone Numbers Field Component
 * 
 * Manages an array of phone numbers with add/remove, primary selection, and PhoneLabel enum.
 */
export function PhoneNumbersField({ name = 'phoneNumbers', mode = 'create' }) {
  const { control, watch, setValue } = useFormContext();
  const { fields, append, remove } = useFieldArray({
    control,
    name,
  });

  const phoneNumbers = watch(name) || [];

  // Find primary phone index from form state
  const primaryIndexFromForm = useMemo(() => {
    const index = phoneNumbers.findIndex((p) => p?.isPrimary === true);
    return index >= 0 ? index : (phoneNumbers.length > 0 ? 0 : -1);
  }, [phoneNumbers]);

  // Local state to track selected primary (for immediate UI updates)
  const [selectedPrimaryIndex, setSelectedPrimaryIndex] = useState(primaryIndexFromForm);

  // Sync local state with form state
  useEffect(() => {
    setSelectedPrimaryIndex(primaryIndexFromForm);
  }, [primaryIndexFromForm]);

  // Handle add phone
  const handleAdd = useCallback(() => {
    const isFirstPhone = phoneNumbers.length === 0;
    const newPhone = {
      phoneNumber: '',
      isPrimary: isFirstPhone, // First phone is primary by default
      phoneLabel: null,
      ...(mode === 'edit' && {
        id: '', // Will be generated by backend for new phones
        branchId: '',
        isActive: true,
      }),
    };
    
    append(newPhone);
    
    // Update local state if this is the first phone (becomes primary)
    if (isFirstPhone) {
      setSelectedPrimaryIndex(0);
    }
  }, [append, phoneNumbers.length, mode]);

  // P0-027 FIX: Track if we need to set first phone as primary after removal
  const [shouldSetPrimaryAfterRemove, setShouldSetPrimaryAfterRemove] = useState(false);
  const previousFieldsLength = useRef(fields.length);
  
  // Handle remove phone
  const handleRemove = useCallback(
    (index) => {
      const wasPrimary = phoneNumbers[index]?.isPrimary;
      const willHavePhones = phoneNumbers.length > 1;
      
      remove(index);
      
      // If removed phone was primary and there are remaining phones, mark for primary update
      if (wasPrimary && willHavePhones) {
        setShouldSetPrimaryAfterRemove(true);
      } else if (phoneNumbers.length === 1) {
        // If this was the last phone, reset primary index
        setSelectedPrimaryIndex(-1);
      }
    },
    [remove, phoneNumbers.length]
  );
  
  // P0-027 FIX: Use useEffect to handle primary phone update when fields array length decreases
  useEffect(() => {
    if (shouldSetPrimaryAfterRemove && fields.length < previousFieldsLength.current && fields.length > 0) {
      // Fields array has decreased, remove completed - set first phone as primary
      setValue(`${name}.0.isPrimary`, true, { shouldValidate: true });
      setSelectedPrimaryIndex(0);
      setShouldSetPrimaryAfterRemove(false);
    }
    previousFieldsLength.current = fields.length;
  }, [fields.length, shouldSetPrimaryAfterRemove, setValue, name]);

  // Handle primary change
  const handlePrimaryChange = useCallback(
    (event) => {
      const newPrimaryIndex = Number(event.target.value);
      const currentPhones = phoneNumbers || [];
      
      // Update local state immediately for UI responsiveness
      setSelectedPrimaryIndex(newPrimaryIndex);
      
      // Update all phones: set selected one as primary, others as not primary
      currentPhones.forEach((phone, i) => {
        const shouldBePrimary = i === newPrimaryIndex;
        setValue(`${name}.${i}.isPrimary`, shouldBePrimary, { 
          shouldValidate: false,
          shouldDirty: true,
        });
      });
    },
    [phoneNumbers, setValue, name]
  );

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
        <Typography variant="subtitle2">Phone Numbers</Typography>
        <Field.Button
          size="small"
          variant="outlined"
          startIcon="mingcute:add-line"
          onClick={handleAdd}
          sx={{ minHeight: 44 }}
        >
          Add Phone
        </Field.Button>
      </Box>

      {fields.length === 0 ? (
        <Typography variant="body2" color="text.secondary" sx={{ fontStyle: 'italic', py: 2 }}>
          No phone numbers added. Click "Add Phone" to add one.
        </Typography>
      ) : (
        <FormControl component="fieldset" fullWidth>
          <RadioGroup 
            value={selectedPrimaryIndex >= 0 ? selectedPrimaryIndex.toString() : ''} 
            onChange={handlePrimaryChange}
          >
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {fields.map((field, index) => (
                <PhoneNumberItem
                  key={field.id}
                  index={index}
                  fieldName={`${name}.${index}`}
                  mode={mode}
                  isPrimary={phoneNumbers[index]?.isPrimary === true}
                  onRemove={() => handleRemove(index)}
                  canRemove={fields.length > 1}
                />
              ))}
            </Box>
          </RadioGroup>
        </FormControl>
      )}
    </Box>
  );
}

// ----------------------------------------------------------------------

/**
 * Phone Number Item Component
 * 
 * Individual phone number card with fields and actions.
 */
function PhoneNumberItem({ index, fieldName, mode, isPrimary, onRemove, canRemove }) {
  return (
    <Card variant="outlined" sx={{ mb: 1 }}>
      <CardContent>
        <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2 }}>
          <Radio value={index.toString()} sx={{ mt: -1 }} />
          
          <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 2 }}>
            <Box sx={{ display: 'flex', gap: 2, alignItems: 'flex-start' }}>
              <Box sx={{ flex: 1 }}>
                <Field.Phone
                  name={`${fieldName}.phoneNumber`}
                  label="Phone Number"
                  placeholder="Enter phone number"
                />
              </Box>
              <Box sx={{ flex: 1 }}>
                <PhoneLabelSelect fieldName={`${fieldName}.phoneLabel`} />
              </Box>
            </Box>

            <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Typography variant="body2" color="text.secondary">
                  Primary phone
                </Typography>
                {isPrimary && (
                  <Label color="primary" variant="soft" sx={{ fontSize: '0.75rem' }}>
                    Primary
                  </Label>
                )}
              </Box>
              {mode === 'edit' && (
                <Field.Switch
                  name={`${fieldName}.isActive`}
                  label="Active"
                />
              )}
            </Box>
          </Box>

          {canRemove && (
            <IconButton
              color="error"
              onClick={onRemove}
              sx={{ minWidth: 44, minHeight: 44 }}
              aria-label="Remove phone"
            >
              <Iconify icon="solar:trash-bin-trash-bold" />
            </IconButton>
          )}
        </Box>
      </CardContent>
    </Card>
  );
}

// ----------------------------------------------------------------------

/**
 * Phone Label Select Component
 * 
 * Simple select dropdown for PhoneLabel enum (1, 2, 3, or null).
 * Uses Field.Autocomplete to comply with shared component standards.
 * Transforms between object format (for Autocomplete) and primitive format (for form/API).
 */
function PhoneLabelSelect({ fieldName }) {
  const { watch, setValue } = useFormContext();

  // Transform options for Autocomplete (no "None" option)
  const options = useMemo(() => 
    PHONE_LABEL_OPTIONS.map((opt) => ({ value: opt.value, label: opt.label })),
    []
  );

  // Watch the current form value (primitive: number or null)
  const currentValue = watch(fieldName);
  
  // Find the option object that matches the current form value
  const selectedOption = useMemo(() => {
    if (currentValue === null || currentValue === undefined) return null;
    return options.find((opt) => opt.value === currentValue) || null;
  }, [currentValue, options]);

  return (
    <Field.Autocomplete
      name={fieldName}
      label="Phone Label"
      options={options}
      value={selectedOption}
      getOptionLabel={(option) => {
        if (!option) return '';
        return option.label || '';
      }}
      isOptionEqualToValue={(option, value) => {
        if (!option || !value) return option === value;
        return option.value === value.value;
      }}
      slotProps={{
        textField: {
          placeholder: 'Select label (optional)',
        },
      }}
      onChange={(event, newValue) => {
        // Override default onChange to transform from option object to primitive value
        // Field.Autocomplete would normally store the object, but we need the primitive
        // If newValue is null (cleared), set form value to null
        const primitiveValue = newValue?.value ?? null;
        setValue(fieldName, primitiveValue, { shouldValidate: true });
      }}
    />
  );
}

