import { z as zod } from 'zod';
import { isValidPhoneNumber } from 'react-phone-number-input/input';

// ----------------------------------------------------------------------

/**
 * Phone number schema (reusable)
 */
const phoneNumberSchema = zod.object({
  phoneNumber: zod
    .string()
    .min(1, 'Phone number is required')
    .refine(
      (val) => isValidPhoneNumber(val),
      'Please enter a valid phone number'
    ),
  isPrimary: zod.boolean().default(false),
  label: zod.string().nullable().optional(),
});

// ----------------------------------------------------------------------

/**
 * Create tenant schema
 */
export const createTenantSchema = zod.object({
  name: zod
    .string()
    .min(1, 'Name is required')
    .max(200, 'Name must be 200 characters or less'),
  description: zod
    .string()
    .max(1000, 'Description must be 1000 characters or less')
    .nullable()
    .optional(),
  phoneNumbers: zod
    .array(phoneNumberSchema)
    .nullable()
    .optional()
    .refine(
      (phones) => {
        if (!phones || phones.length === 0) return true;
        const primaryCount = phones.filter((p) => p.isPrimary).length;
        return primaryCount <= 1;
      },
      'Only one phone number can be marked as primary'
    ),
});

// ----------------------------------------------------------------------

/**
 * Update phone number schema (includes id fields for phones)
 * For new phones, id and tenantId can be empty strings (will be generated by backend)
 * For existing phones, they must be valid UUIDs
 */
const updatePhoneNumberSchema = phoneNumberSchema.extend({
  id: zod.union([
    zod.string().uuid('Invalid phone ID'),
    zod.literal(''), // Empty string for new phones
  ]),
  tenantId: zod.union([
    zod.string().uuid('Invalid tenant ID'),
    zod.literal(''), // Empty string for new phones
  ]),
  isActive: zod.boolean(),
});

// ----------------------------------------------------------------------

/**
 * Update tenant schema
 */
export const updateTenantSchema = zod.object({
  name: zod
    .string()
    .min(1, 'Name is required')
    .max(200, 'Name must be 200 characters or less'),
  description: zod
    .string()
    .max(1000, 'Description must be 1000 characters or less')
    .nullable()
    .optional(),
  ownerId: zod.string().uuid('Invalid owner ID').nullable().optional(),
  isActive: zod.boolean(),
  phoneNumbers: zod
    .array(updatePhoneNumberSchema)
    .nullable()
    .optional()
    .refine(
      (phones) => {
        if (!phones || phones.length === 0) return true;
        const primaryCount = phones.filter((p) => p.isPrimary).length;
        return primaryCount <= 1;
      },
      'Only one phone number can be marked as primary'
    ),
});

