import { z as zod } from 'zod';
import { isValidPhoneNumber } from 'react-phone-number-input/input';

// ----------------------------------------------------------------------

/**
 * Phone number schema for create operations
 */
const phoneNumberSchema = zod.object({
  phoneNumber: zod
    .string()
    .min(1, 'Phone number is required')
    .refine(
      (val) => isValidPhoneNumber(val),
      'Please enter a valid phone number'
    ),
  isPrimary: zod.boolean().default(false),
  phoneLabel: zod.union([
    zod.literal(1), // Main
    zod.literal(2), // Delivery
    zod.literal(3), // Reservations
    zod.null(),
  ]).optional(),
});

// ----------------------------------------------------------------------

/**
 * Create branch schema
 */
export const createBranchSchema = zod.object({
  tenantId: zod.preprocess(
    (val) => {
      // If it's an object with an id property, extract the id
      if (typeof val === 'object' && val !== null && 'id' in val) {
        return val.id;
      }
      // Otherwise, use the value as-is (should be a string UUID)
      return val;
    },
    zod.string().uuid('Invalid tenant ID')
  ),
  name: zod
    .string()
    .min(1, 'Name is required')
    .max(200, 'Name must be 200 characters or less'),
  address: zod.string().max(1000, 'Address must be 1000 characters or less').nullable().optional(),
  phoneNumbers: zod
    .array(phoneNumberSchema)
    .nullable()
    .optional()
    .refine(
      (phones) => {
        if (!phones || phones.length === 0) return true;
        const primaryCount = phones.filter((p) => p.isPrimary).length;
        return primaryCount <= 1;
      },
      'Only one phone number can be marked as primary'
    ),
});

// ----------------------------------------------------------------------

/**
 * Update phone number schema (includes id fields for phones)
 * For new phones, id and branchId can be empty strings (will be generated by backend)
 * For existing phones, they must be valid UUIDs
 */
const updatePhoneNumberSchema = phoneNumberSchema.extend({
  id: zod.union([
    zod.string().uuid('Invalid phone ID'),
    zod.literal(''), // Empty string for new phones
  ]),
  branchId: zod.union([
    zod.string().uuid('Invalid branch ID'),
    zod.literal(''), // Empty string for new phones
  ]),
  isActive: zod.boolean(),
});

// ----------------------------------------------------------------------

/**
 * Update branch schema
 */
export const updateBranchSchema = zod.object({
  tenantId: zod.preprocess(
    (val) => {
      // If it's an object with an id property, extract the id
      if (typeof val === 'object' && val !== null && 'id' in val) {
        return val.id;
      }
      // Otherwise, use the value as-is (should be a string UUID)
      return val;
    },
    zod.string().uuid('Invalid tenant ID')
  ),
  name: zod
    .string()
    .min(1, 'Name is required')
    .max(200, 'Name must be 200 characters or less'),
  address: zod.string().max(1000, 'Address must be 1000 characters or less').nullable().optional(),
  isActive: zod.boolean(),
  phoneNumbers: zod
    .array(updatePhoneNumberSchema)
    .nullable()
    .optional()
    .refine(
      (phones) => {
        if (!phones || phones.length === 0) return true;
        const primaryCount = phones.filter((p) => p.isPrimary).length;
        return primaryCount <= 1;
      },
      'Only one phone number can be marked as primary'
    ),
});

